name: Deploy MTA-STS

on:
  push:
    branches: [main]
    paths:
      - 'mta-sts/**'
      - '.github/workflows/mta-sts.yml'
  workflow_dispatch:

permissions:
  contents: read
  deployments: write

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Publish to Cloudflare Pages
        uses: cloudflare/wrangler-action@v4
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy mta-sts --project-name=mta-sts-mdekort-nl
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
